apiVersion: v1
kind: Service
metadata:
  name: deployment-svc
  labels:
    app: krateo.io
    component: deployment
spec:
  selector:
    component: deployment
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080