apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: krateo.io
    component: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: deployment
  template:
    metadata:
      labels:
        component: deployment
    spec:
      containers:
        - name: deployment
          image: {{ .Values.registry.images.deployment }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 30
          env:
            - name: 'LOG_LEVEL'
              value: {{ .Values.log.level }}
            - name: 'TEMPLATE_URI'
              value: {{ .Values.uris.template }}
            - name: 'ENDPOINT_URI'
              value: {{ .Values.uris.endpoint }}
            - name: 'GIT_URI'
              value: {{ .Values.uris.git }}
            - name: 'ARGOCD_URI'
              value: {{ .Values.uris.argocd }}
            - name: 'MONGODB_URI'
              valueFrom:
                secretKeyRef:
                  name: krateo-secret
                  key: MONGODB_URI
      imagePullSecrets:
        - name: registry-credentials
